env: standard
runtime: nodejs18
instance_class: F1
service: default
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  max_instances: 1
handlers:
  - url: /.*
    secure: always
    script: auto