import Head from "next/head";

import { ContactForm, Introduction, Rules } from "@/features/contact";
import { ContactLayout } from "@/layouts/ContactLayout";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Explow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactLayout>
        <Introduction />
        <ContactLayout.Section>
          <div>
            <ContactLayout.Title>
              Nos conte sobre o seu projeto 🛸
            </ContactLayout.Title>
            <ContactLayout.Description>
              Nos conte um pouco sobre o seu projeto e como poderemos te ajudar,
              entraremos em contato com você hoje pelo seu número de WhatsApp
              para desenvolver um projeto de outro mundo!
            </ContactLayout.Description>
          </div>
          <ContactLayout.FormGroup>
            <ContactForm />
            <Rules />
          </ContactLayout.FormGroup>
        </ContactLayout.Section>
      </ContactLayout>
    </>
  );
}
