import Head from "next/head";

import { ContactForm, Introduction } from "@/features/contact";
import { ContactLayout } from "@/layouts/ContactLayout";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Explow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactLayout>
        <Introduction />
        <ContactForm />
      </ContactLayout>
    </>
  );
}
