import Head from "next/head";

import { DefaultLayout, Faq } from "@/layouts";
import {
  Introduction,
  OurCustomers,
  OurMethodology,
  OurPartners,
  OurServices,
  OurStory,
  Testimonials,
  WhyWeAre,
} from "@/features/home";
import { Grid } from "@/ui";

export default function Home() {
  return (
    <>
      <Head>
        <title>Explow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Introduction />
        <OurStory />
        <OurPartners />
        <Testimonials />
        <OurServices />
        <OurMethodology />
        <WhyWeAre />
        <OurCustomers />
        <Grid>
          <Faq />
        </Grid>
      </DefaultLayout>
    </>
  );
}
