import Head from "next/head";

import { DefaultLayout } from "@/layouts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Explow | Next.js Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <h1>Next.js Template</h1>
      </DefaultLayout>
    </>
  );
}
